[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/openai/edit"
  to = "/.netlify/functions/edit"
  status = 200

[[redirects]]
  from = "/generate/api/openai/edit"
  to = "/.netlify/functions/edit"
  status = 200
